### ISSUE TITLE
All twitter actions do not support optional parameters

### ISSUE THREAD

**Issue by muthulee** [wso2-ballerina/module-twitter#13]
Cannot pass any optional parameters specified in the API [1] in all the twitter actions.

[1] https://dev.twitter.com/rest/reference/get/search/tweets

**Comment by Biruntha** [comment]
Supported all the optional params with this PR https://github.com/wso2-ballerina/module-twitter/pull/83

**Comment by anupama-pathirage** [comment]
Closing as we are no longer maintaining this code.
