### ISSUE TITLE
Versions Compatible Issues

### ISSUE THREAD

**Issue by fargozhu** [wso2-ballerina/module-twitter#71]
**Description:**
I installed Ballerina stable version (0.982.0) 'cause I am a responsible person🤖  and I was giving it a try when I face the wall with twitter module:

> your ballerina version does not support for module: wso2/twitter:*. following versions are supported: 0.9.19

First, I do not understand if the 0.9.19 version is related with Ballerina or Twitter module? Both are using 0.xxx.x semantic which makes this situation weird...

Second, the README says it's compatible with Ballerina version 0.983.0 which is a **alpha version**. Should be, at least, compatible with a stable version?

**Comment by hemikak** [comment]
Hi @fargozhu ,

0.9.19 is the version of the twitter module. If you check central(https://central.ballerina.io/wso2/twitter/0.9.19) it says that ballerina 0.982.0 version supports 0.9.19 version of the twitter module. You can import the 0.9.19 version of the twitter module using a Ballerina.toml file(https://ballerina.io/learn/how-to-structure-ballerina-code/#module-version-dependency)

The 0.9.19 twitter version is not backward compatible.

**Comment by NatashaWso2** [comment]
@fargozhu closing this issue as per the above comment. Please reopen if you think there are any other areas to be fixed or improved.
