### ISSUE TITLE
Twitter component does not catch misconfiguration

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2-ballerina/module-twitter#75]
**Description:**
Please refer https://github.com/ballerina-platform/ballerina-lang/issues/12086 for more details. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Biruntha** [comment]
Fixed in PR #83

**Comment by anupama-pathirage** [comment]
Closing as we are no longer maintaining this code.
